"""create equipment, sensor_reading, work_order, risk_score tables

Revision ID: aa0f4a9c09c9
Revises: 
Create Date: 2026-07-28 19:03:04.997638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0f4a9c09c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criticality_tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_plant_id'), 'equipment', ['plant_id'], unique=False)
    op.create_table('risk_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('REAL_TIME', 'BATCH', name='risk_score_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_score_created_at'), 'risk_score', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_score_equipment_id'), 'risk_score', ['equipment_id'], unique=False)
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_reading_equipment_id'), 'sensor_reading', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensor_reading_timestamp'), 'sensor_reading', ['timestamp'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('opened_by', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'ELEVATED', 'URGENT', name='work_order_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='work_order_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_equipment_id'), 'work_order', ['equipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_equipment_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_sensor_reading_timestamp'), table_name='sensor_reading')
    op.drop_index(op.f('ix_sensor_reading_equipment_id'), table_name='sensor_reading')
    op.drop_table('sensor_reading')
    op.drop_index(op.f('ix_risk_score_equipment_id'), table_name='risk_score')
    op.drop_index(op.f('ix_risk_score_created_at'), table_name='risk_score')
    op.drop_table('risk_score')
    op.drop_index(op.f('ix_equipment_plant_id'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
    # Postgres ENUM types are separate objects from the columns that use
    # them — dropping the tables above does not drop these, and a
    # re-upgrade fails with "type already exists" unless they're
    # dropped explicitly here.
    sa.Enum(name='work_order_priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='work_order_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_score_source').drop(op.get_bind(), checkfirst=True)
