"""add work order approval fields

Revision ID: f75f42177efa
Revises: aa0f4a9c09c9
Create Date: 2026-08-05 18:45:55.012457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75f42177efa'
down_revision: Union[str, None] = 'aa0f4a9c09c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('recommended_priority', sa.Enum('ROUTINE', 'ELEVATED', 'URGENT', name='work_order_priority'), nullable=True))
    op.add_column('work_order', sa.Column('priority_approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_order', sa.Column('priority_approved_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'priority_approved_by')
    op.drop_column('work_order', 'priority_approved_at')
    op.drop_column('work_order', 'recommended_priority')
    # ### end Alembic commands ###
